coverage:
  status:
    project:
      default:
        target: auto  # This will use the coverage of the base branch as the target
        threshold: 1% # Allow coverage to drop by 1% while still passing
    patch:
      default:
        target: auto
        threshold: 1%

ignore:
  # Test files
  - "tests/**/*"
  - "**/tests/**/*"
  - "**/*.test.*"
  - "**/*_test.*"
  
  # Virtual environments
  - "venv/**/*"
  - "env/**/*"
  - ".venv/**/*"
  
  # Cache directories
  - "**/__pycache__/**/*"
  - "**/.pytest_cache/**/*"
  
  # Custom folders to ignore
  - "src/zensvi/utils/**/*"
  - "src/zensvi/download/mapillary/**/*"
  - "src/zensvi/download/utils/**/*"
  - "src/zensvi/cv/depth_estimation/depth_anything/**/*"
  - "src/zensvi/cv/depth_estimation/zoedepth/**/*"
  - "src/zensvi/cv/depth_estimation/torchhub/**/*"

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false

parsers:
  python:
    exclude_lines:
      - pragma: no cover
      - def __repr__
      - raise NotImplementedError
      - if __name__ == .__main__.:
      - pass
      - raise AssertionError
