from .glare import ClassifierGlare
from .lighting import ClassifierLighting
from .panorama import ClassifierPanorama
from .perception import ClassifierPerception
from .places365 import ClassifierPlaces365
from .platform import ClassifierPlatform
from .quality import ClassifierQuality
from .reflection import ClassifierReflection
from .view_direction import ClassifierViewDirection
from .weather import ClassifierWeather
