name: Pull Request Checks

on:
  pull_request:
    branches: [ main ]

jobs:
  pr-checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pydocstyle

    - name: Check docstrings
      run: |
        pydocstyle src/zensvi

    - name: Check file changes in tests/
      run: |
        # Checks for any upload in tests/
        CHANGED_FILES=$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} -- tests/)
        if [ -n "$CHANGED_FILES" ]; then
          echo "Files changed in tests/:"
          echo "$CHANGED_FILES"
          echo "Check passed: Files were modified in tests/."
        else
          echo "No files were changed in tests/."
          exit 1
        fi
